var TIPUS_VIA_CADASTRE = [
{"tv":"AG","nom":"AGREGADO"},
{"tv":"AL","nom":"ALDEA, ALAMEDA"},
{"tv":"AR","nom":"AREA, ARRABAL"},
{"tv":"AU","nom":"AUTOPISTA"},
{"tv":"AV","nom":"AVENIDA"},
{"tv":"AY","nom":"ARROYO"},
{"tv":"BJ","nom":"BAJADA"},
{"tv":"BO","nom":"BARRIO"},
{"tv":"BR","nom":"BARRANCO"},
{"tv":"CA","nom":"CAÑADA"},
{"tv":"CG","nom":"COLEGIO, CIGARRAL"},
{"tv":"CH","nom":"CHALET"},
{"tv":"CI","nom":"CINTURON"},
{"tv":"CJ","nom":"CALLEJA, CALLEJON"},
{"tv":"CL","nom":"CALLE"},
{"tv":"CM","nom":"CAMINO, CARMEN"},
{"tv":"CN","nom":"COLONIA"},
{"tv":"CO","nom":"CONCEJO, COLEGIO"},
{"tv":"CP","nom":"CAMPA, CAMPO"},
{"tv":"CR","nom":"CARRETERA, CARRERA"},
{"tv":"CS","nom":"CASERIO"},
{"tv":"CT","nom":"CUESTA, COSTANILLA"},
{"tv":"CU","nom":"CONJUNTO"},
{"tv":"DE","nom":"DETRÁS"},
{"tv":"DP","nom":"DIPUTACION"},
{"tv":"DS","nom":"DISEMINADOS"},
{"tv":"ED","nom":"EDIFICIOS"},
{"tv":"EM","nom":"EXTRAMUROS"},
{"tv":"EN","nom":"ENTRADA, ENSANCHE"},
{"tv":"ER","nom":"EXTRARRADIO"},
{"tv":"ES","nom":"ESCALINATA"},
{"tv":"EX","nom":"EXPLANADA"},
{"tv":"FC","nom":"FERROCARRIL"},
{"tv":"FN","nom":"FINCA"},
{"tv":"GL","nom":"GLORIETA"},
{"tv":"GR","nom":"GRUPO"},
{"tv":"GV","nom":"GRAN VIA"},
{"tv":"HT","nom":"HUERTA, HUERTO"},
{"tv":"JR","nom":"JARDINES"},
{"tv":"LD","nom":"LADO, LADERA"},
{"tv":"LG","nom":"LUGAR"},
{"tv":"MC","nom":"MERCADO"},
{"tv":"ML","nom":"MUELLE"},
{"tv":"MN","nom":"MUNICIPIO"},
{"tv":"MS","nom":"MASIAS"},
{"tv":"MT","nom":"MONTE"},
{"tv":"MZ","nom":"MANZANA"},
{"tv":"PB","nom":"POBLADO"},
{"tv":"PD","nom":"PARTIDA"},
{"tv":"PJ","nom":"PASAJE, PASADIZO"},
{"tv":"PL","nom":"POLIGONO"},
{"tv":"PM","nom":"PARAMO"},
{"tv":"PQ","nom":"PARROQUIA, PARQUE"},
{"tv":"PR","nom":"PROLONGACION, CONTINUAC."},
{"tv":"PS","nom":"PASEO"},
{"tv":"PT","nom":"PUENTE"},
{"tv":"PZ","nom":"PLAZA"},
{"tv":"QT","nom":"QUINTA"},
{"tv":"RB","nom":"RAMBLA"},
{"tv":"RC","nom":"RINCON, RINCONA"},
{"tv":"RD","nom":"RONDA"},
{"tv":"RM","nom":"RAMAL"},
{"tv":"RP","nom":"RAMPA"},
{"tv":"RR","nom":"RIERA"},
{"tv":"RU","nom":"RUA"},
{"tv":"SA","nom":"SALIDA"},
{"tv":"SD","nom":"SENDA"},
{"tv":"SL","nom":"SOLAR"},
{"tv":"SN","nom":"SALON"},
{"tv":"SU","nom":"SUBIDA"},
{"tv":"TN","nom":"TERRENOS"},
{"tv":"TO","nom":"TORRENTE"},
{"tv":"TR","nom":"TRAVESIA"},
{"tv":"UR","nom":"URBANIZACION"},
{"tv":"VR","nom":"VEREDA"},
{"tv":"CY","nom":"CALEYA"}
];